trigger: none

pool:
  vmImage: 'ubuntu-20.04'

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  - job:
    displayName: Create Docker image
    steps:
      - script: |
          git clone https://github.com/keycloak/keycloak-containers.git  
        displayName: Checkout Keycloak Containers repository
      - script: |
          git config --global user.email "johnny.k.hansson@gmail.com"
          git config --global user.name "Johnny Cederholm"
        displayName: Setup name and email for git
      - script: |
          git am < ../../image.patch
        workingDirectory: keycloak-containers/server
        displayName: Apply base image patch
      - task: Docker@2
        displayName: Docker Hub login
        inputs:
          containerRegistry: 'Docker Hub'
          command: 'login'
      - script: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --name builder --use
          docker buildx inspect builder --bootstrap
          docker buildx build --platform linux/arm/v7 \
            -t johnnyhansson/keycloak:$(build.buildNumber) \
            -t johnnyhansson/keycloak:latest \
          --push \
          .
        displayName: Build and push multiarch Docker image
        workingDirectory: keycloak-containers/server