trigger: none

pool: 
  vmImage: 'ubuntu-20.04'

jobs:
  - job:
    displayName: Create Docker image
    steps:
      - script: |
          git clone https://github.com/keycloak/keycloak-containers.git  
        displayName: Checkout Keycloak Containers repository
      - script: |
          git config --global user.email "johnny.k.hansson@gmail.com"
          git config --global user.name "Johnny Cederholm"
      - script: |
          git am < ../../image.patch
        workingDirectory: keycloak-containers/server
      - script: |
          git log